### ISSUE TITLE
Hints typo error

### ISSUE THREAD

**Issue by PhilippeRoy** [codio/tutorial_nodeschool_expressworks#2]
Your hint is as follows:

HINTS

This you someone can call static middleware:

  app.use(express.static(path.join(__dirname, 'public')));

For this exercise ExpressWorks will pass you the path:

  app.use(express.static(process.argv[3]||path.join(__dirname, 'public')));
# 

I believe you were intending to write: 
"This is how someone can call static middleware"

**Comment by ghost** [comment]
Thanks.. good spot.. now updated
